const test = require('node:test');
const assert = require('node:assert/strict');
const path = require('node:path');
const mongoose = require('mongoose');
const jwt = require('jsonwebtoken');
const bcrypt = require('bcrypt');
const { MongoMemoryReplSet } = require('mongodb-memory-server');
const User = require('../src/models/User');
const RegistrationRequest = require('../src/models/RegistrationRequest');

test('registration requires admin approval, preserves LGU details and prevents duplicate or unauthorized reviews', { timeout: 90000 }, async t => {
  const database = await MongoMemoryReplSet.create({ replSet: { count: 1 }, binary: { systemBinary: path.resolve(__dirname, '../node_modules/.cache/mongodb-memory-server/mongod-x64-win32-8.2.6.exe') } });
  await mongoose.connect(database.getUri());
  await Promise.all([User.init(), RegistrationRequest.init()]);
  const server = require('../src/app').listen(0);
  t.after(async () => { server.closeAllConnections(); await new Promise(resolve => server.close(resolve)); await mongoose.disconnect(); await database.stop(); });
  const admin = await User.create({ firstName: 'Admin', lastName: 'Test', username: 'registration-admin', email: 'registration-admin@example.test', password: 'test', office: 'Supply', division: 'Supply', role: 'admin' });
  const regular = await User.create({ firstName: 'User', lastName: 'Test', username: 'registration-user', email: 'registration-user@example.test', password: 'test', office: 'Supply', division: 'Supply', role: 'user' });
  const request = async (url, method = 'GET', body, actor) => {
    const response = await fetch(`http://127.0.0.1:${server.address().port}/api${url}`, { method, headers: { 'Content-Type': 'application/json', ...(actor ? { Authorization: `Bearer ${jwt.sign({ id: actor._id }, process.env.JWT_SECRET || 'dev-secret')}` } : {}) }, ...(body ? { body: JSON.stringify(body) } : {}) });
    return { status: response.status, body: await response.json() };
  };
  const payload = { firstName: 'Applicant', middleName: 'LGU', lastName: 'Test', username: 'lgu-applicant', email: 'applicant@example.test', password: 'Applicant123!', confirmPassword: 'Applicant123!', office: 'Municipal Planning Office', division: 'Planning', position: 'Administrative Officer', role: 'admin', permissions: ['canManageUsers'] };
  assert.equal((await request('/registration', 'POST', { ...payload, position: '   ' })).status, 400);
  assert.equal((await request('/registration', 'POST', { ...payload, confirmPassword: 'different' })).status, 400);
  const submitted = await request('/registration', 'POST', payload);
  assert.equal(submitted.status, 201);
  assert.equal(await User.countDocuments({ username: payload.username }), 0, 'Pending request is not an active account');
  assert.equal((await request('/auth/login', 'POST', { identifier: payload.username, password: payload.password })).status, 401);
  assert.equal((await request('/registration', 'POST', payload)).status, 409);
  assert.equal((await request('/registration')).status, 401);
  assert.equal((await request('/registration', 'GET', undefined, regular)).status, 403);
  const listing = await request('/registration', 'GET', undefined, admin);
  assert.equal(listing.body.data.length, 1);
  const pending = listing.body.data[0];
  assert.equal(pending.position, payload.position);
  assert.equal(pending.passwordHash, undefined);
  assert.equal(pending.password, undefined);
  assert.equal((await request(`/registration/${pending._id}/approve`, 'POST', {}, regular)).status, 403);
  const approved = await request(`/registration/${pending._id}/approve`, 'POST', {}, admin);
  assert.equal(approved.status, 200, JSON.stringify(approved.body));
  const account = await User.findOne({ username: payload.username });
  assert.equal(account.role, 'user');
  assert.equal(account.position, payload.position);
  assert.equal(account.office, payload.office);
  assert.ok(!account.permissions.includes('canManageUsers'));
  assert.equal(await bcrypt.compare(payload.password, account.password), true);
  assert.equal((await request('/auth/login', 'POST', { identifier: payload.username, password: payload.password })).status, 200);
  assert.equal((await request(`/registration/${pending._id}/approve`, 'POST', {}, admin)).status, 409);
  const rejectedPayload = { ...payload, username: 'rejected-applicant', email: 'rejected@example.test' };
  assert.equal((await request('/registration', 'POST', rejectedPayload)).status, 201);
  const rejected = await RegistrationRequest.findOne({ username: rejectedPayload.username });
  assert.equal((await request(`/registration/${rejected._id}/reject`, 'POST', { reason: 'Office details require correction' }, admin)).status, 200);
  assert.equal(await User.countDocuments({ username: rejectedPayload.username }), 0);
  assert.equal((await request(`/registration/${rejected._id}/approve`, 'POST', {}, admin)).status, 409);
  assert.equal((await request('/registration', 'GET', undefined, admin)).body.data.length, 0);
});
