const test = require('node:test');
const assert = require('node:assert/strict');
const path = require('node:path');
const express = require('express');
const jwt = require('jsonwebtoken');
const mongoose = require('mongoose');
const { MongoMemoryReplSet } = require('mongodb-memory-server');
const User = require('../src/models/User');
const Item = require('../src/models/Item');
const Ris = require('../src/models/RequisitionIssueSlip');
const Inventory = require('../src/models/Inventory');
const PropertyReturnSlip = require('../src/models/PropertyReturnSlip');
const ReturnedSupply = require('../src/models/ReturnedSupply');

test('user requests and return results are scoped to the signed-in account', { timeout: 60000 }, async t => {
  const database = await MongoMemoryReplSet.create({ replSet: { count: 1 }, binary: { systemBinary: path.resolve(__dirname, '../node_modules/.cache/mongodb-memory-server/mongod-x64-win32-8.2.6.exe') } });
  await mongoose.connect(database.getUri());
  await PropertyReturnSlip.init();
  const app = express(); app.use(express.json()); app.use('/ris', require('../src/routes/ris')); app.use('/prs', require('../src/routes/returns'));
  const server = app.listen(0);
  t.after(async () => { await new Promise(resolve => server.close(resolve)); await mongoose.disconnect(); await database.stop(); });
  const makeUser = (username, role = 'user') => User.create({ username, firstName: username, lastName: 'Test', email: `${username}@example.test`, password: 'test', office: 'Supply', division: 'Supply', role, permissions: ['canViewRIS'] });
  const user = await makeUser('user1'); const other = await makeUser('user2'); const admin = await makeUser('admin', 'admin');
  const request = async (person, route, method = 'GET', body) => {
    const response = await fetch(`http://127.0.0.1:${server.address().port}${route}`, { method, headers: { Authorization: `Bearer ${jwt.sign({ id: person._id }, process.env.JWT_SECRET || 'dev-secret')}`, 'Content-Type': 'application/json' }, body: body ? JSON.stringify(body) : undefined });
    return { status: response.status, body: await response.json() };
  };
  const stock = await Item.create({ stockNumber: 'ST-1', description: 'Chair', unit: 'piece', cost: 100, quantityOnHand: 5 });
  await Inventory.create({ item: stock._id, quantity: 5, unitCost: 100, assetCost: 500 });
  const created = await request(user, '/ris/my-requests', 'POST', { purpose: 'Office use', items: [{ stockNumber: 'ST-1', quantityRequested: 2 }], status: 'ISSUED', requestedBy: { user: other._id } });
  assert.equal(created.status, 201);
  assert.equal(created.body.data.status, 'PENDING_REVIEW');
  assert.equal(created.body.data.requestedBy.user, String(user._id));
  assert.equal((await request(other, '/ris')).body.data.length, 0);
  assert.equal((await request(user, '/ris/my-returns')).body.data.length, 0);
  let recorded = (await request(user, '/ris/my-items')).body.data;
  assert.equal(recorded.length, 1);
  assert.equal(recorded[0].status, 'Pending admin review');
  assert.equal(recorded[0].quantityRequested, 2);
  assert.equal(recorded[0].quantityIssued, 0);
  assert.equal(recorded[0].issued, false);
  assert.equal((await request(other, '/ris/my-items')).body.data.length, 0);
  const id = created.body.data._id;
  assert.equal((await request(user, `/ris/${id}/review`, 'POST', {})).status, 403);
  assert.equal((await request(admin, `/ris/${id}/review`, 'POST', {})).status, 200);
  assert.equal((await request(admin, `/ris/${id}/approve`, 'POST', {})).status, 200);
  assert.equal((await request(user, '/ris/my-returns')).body.data.length, 1);
  recorded = (await request(user, '/ris/my-items')).body.data;
  assert.equal(recorded[0].status, 'Not returned');
  assert.equal(recorded[0].quantityIssued, 2);
  assert.equal((await request(admin, `/ris/${id}/issue`, 'POST', {})).status, 400);
  const ris = await Ris.findById(id);
  const linked = (await request(user, '/ris/my-returns')).body.data[0];
  assert.equal(linked.formType, 'ICS');
  assert.ok(linked.documentNumber);
  assert.equal(linked.formId, String(ris.inventoryCustodianSlip));
  const issuedView = (await request(user, '/ris/my-items')).body.data[0];
  assert.equal(issuedView.issued, true);
  assert.equal(issuedView.quantityIssued, 2);
  assert.equal(issuedView.formType, 'ICS');
  assert.equal((await request(admin, `/ris/${id}`, 'PUT', { requestedBy: { user: other._id }, status: 'APPROVED' })).status, 409);
  assert.equal((await request(user, '/ris/my-returns')).body.data[0].status, 'Not returned');
  let returnable = (await request(admin, '/ris/returnable-items')).body.data;
  assert.equal(returnable.find(record => record._id === id).items[0].quantityRemaining, 2);
  assert.equal(returnable.find(record => record._id === id).items[0].unitCost, 100);
  assert.equal((await request(user, '/ris/returnable-items')).status, 403);
  const payload = { lguName: 'Carigara', items: [{ ris: ris._id, risItem: ris.items[0]._id, quantity: 1, description: 'Chair' }], returnedTo: { name: 'Admin', date: new Date() } };
  assert.equal((await request(user, '/prs', 'POST', payload)).status, 403);
  assert.equal((await request(admin, '/prs', 'POST', payload)).status, 201);
  let result = (await request(user, '/ris/my-returns')).body.data[0];
  assert.equal(result.status, 'Partially returned'); assert.equal(result.quantityRemaining, 1);
  returnable = (await request(admin, '/ris/returnable-items')).body.data;
  assert.equal(returnable.find(record => record._id === id).items[0].quantityRemaining, 1);
  assert.equal((await request(other, '/ris/my-returns')).body.data.length, 0);
  assert.equal((await request(admin, '/prs', 'POST', { ...payload, items: [{ ...payload.items[0], quantity: 2 }] })).status, 400);
  assert.equal((await request(admin, '/prs', 'POST', payload)).status, 201);
  result = (await request(user, '/ris/my-returns')).body.data[0];
  assert.equal(result.status, 'Successfully returned'); assert.equal(result.quantityRemaining, 0);
  assert.equal((await request(admin, '/ris/returnable-items')).body.data.some(record => record._id === id), false);
  const slips = (await request(admin, '/prs')).body.data;
  assert.equal((await request(admin, `/prs/${slips[0]._id}`, 'PUT', payload)).status, 200);
  assert.equal((await request(user, '/ris/my-returns')).body.data[0].quantityReturned, 2);

  // Users send only item references and quantities; the server supplies identity and details.
  const second = await Ris.create({ risNumber: 'RIS-SECOND', entityName: 'Carigara', status: 'ISSUED', requestedBy: { user: user._id, name: 'user1 Test' }, receivedBy: { user: user._id, name: 'user1 Test' }, items: [{ stockNumber: 'ST-1', description: 'Chair', unit: 'piece', quantityIssued: 3 }] });
  const submission = { risId: second._id, itemId: second.items[0]._id, quantity: 1, returnedBy: { name: 'Spoofed name' }, description: 'Spoofed item', status: 'RETURNED' };
  assert.equal((await request(other, '/ris/my-returns', 'POST', submission)).status, 404);
  assert.equal((await request(user, '/ris/my-returns', 'POST', { ...submission, quantity: 4 })).status, 400);
  const submitted = await request(user, '/ris/my-returns', 'POST', submission);
  assert.equal(submitted.status, 201);
  assert.equal(submitted.body.data.returnedBy.name, 'user1 Test');
  assert.equal(submitted.body.data.items[0].description, 'Chair');
  assert.equal(submitted.body.data.items[0].mrNumber, 'RIS-SECOND');
  assert.equal(submitted.body.data.items[0].unitValue, 100);
  assert.equal(submitted.body.data.items[0].totalValue, 100);
  assert.equal(submitted.body.data.status, 'PENDING');
  assert.equal(await ReturnedSupply.countDocuments({ prs: submitted.body.data._id }), 0);
  assert.equal((await request(user, '/ris/my-returns', 'POST', submission)).status, 409);
  result = (await request(user, '/ris/my-returns')).body.data.find(row => row.risNumber === 'RIS-SECOND');
  assert.equal(result.status, 'Awaiting admin confirmation'); assert.equal(result.quantityReturned, 0);
  const adminSlip = (await request(admin, '/prs')).body.data.find(row => row._id === submitted.body.data._id);
  assert.equal(adminSlip.returnedBy.name, 'user1 Test');
  assert.equal((await request(user, `/prs/${adminSlip._id}/confirm`, 'POST', {})).status, 403);
  assert.equal((await request(admin, `/prs/${adminSlip._id}/confirm`, 'POST', {})).status, 200);
  assert.equal((await request(admin, `/prs/${adminSlip._id}/confirm`, 'POST', {})).status, 404);
  assert.equal(await ReturnedSupply.countDocuments({ prs: adminSlip._id }), 1);
  result = (await request(user, '/ris/my-returns')).body.data.find(row => row.risNumber === 'RIS-SECOND');
  assert.equal(result.status, 'Partially returned'); assert.equal(result.quantityRemaining, 2);
  const rejected = await request(user, '/ris/my-returns', 'POST', { ...submission, quantity: 2 });
  assert.equal((await request(admin, `/prs/${rejected.body.data._id}/reject`, 'POST', { reason: 'Item not yet received' })).status, 200);
  result = (await request(user, '/ris/my-returns')).body.data.find(row => row.risNumber === 'RIS-SECOND');
  assert.equal(result.quantityReturned, 1); assert.equal(result.pendingReturn, false);
  assert.equal(result.returns[0].rejectionReason, 'Item not yet received');
  const finalReturn = await request(user, '/ris/my-returns', 'POST', { ...submission, quantity: 2 });
  assert.equal(finalReturn.status, 201);
  assert.equal((await request(admin, `/prs/${finalReturn.body.data._id}/confirm`, 'POST', {})).status, 200);
  result = (await request(user, '/ris/my-returns')).body.data.find(row => row.risNumber === 'RIS-SECOND');
  assert.equal(result.status, 'Successfully returned'); assert.equal(result.quantityRemaining, 0);
  for (const stockNumber of ['MANUAL-U123', '', null]) {
    const manual = await request(user, '/ris/my-requests', 'POST', { purpose: 'Office use', items: [{ stockNumber, description: 'Manually described item', unit: 'piece', quantityRequested: 1 }] });
    assert.equal(manual.status, 201, JSON.stringify(manual.body));
    assert.equal(manual.body.data.items[0].stockNumber, stockNumber);
    assert.equal(manual.body.data.items[0].quantityIssued, 0);
    assert.equal(manual.body.data.requestedBy.user, String(user._id));
  }
  const adminPayload = { risNumber: 'ADMIN-RECORDED', entityName: 'Carigara', fundCluster: 'Trust Fund', division: 'Supply', office: 'Supply', responsibilityCenterCode: '001', requestedBy: { name: 'user2 Test' }, receivedBy: { name: 'user2 Test' }, items: [{ stockNumber: 'ST-1', description: 'Chair', quantityRequested: 1, quantityIssued: 1 }] };
  const adminRecord = await request(admin, '/ris', 'POST', adminPayload);
  assert.equal(adminRecord.status, 201);
  assert.equal(adminRecord.body.data.requestedBy.user, String(other._id));
  const immediate = (await request(other, '/ris/my-items')).body.data.find(row => row.risNumber === 'ADMIN-RECORDED');
  assert.ok(immediate);
  assert.equal(immediate.quantityRequested, 1);
  assert.equal(immediate.quantityIssued, 0, 'Planned quantities are not actual issuance');
  assert.equal(immediate.status, 'Pending admin review');
  assert.equal((await request(other, `/ris/${adminRecord.body.data._id}/approve`, 'POST', {})).status, 403);
  assert.equal((await request(admin, `/ris/${adminRecord.body.data._id}/approve`, 'POST', {})).status, 200);
  const approvedRecord = (await request(other, '/ris/my-items')).body.data.find(row => row.risNumber === 'ADMIN-RECORDED');
  assert.equal(approvedRecord.requestStatus, 'ACCOUNTABILITY_LOCKED');
  assert.equal(approvedRecord.status, 'Not returned');
  assert.equal(approvedRecord.quantityIssued, 1);
  assert.equal((await request(admin, `/ris/${adminRecord.body.data._id}/approve`, 'POST', {})).status, 200);
  const returnAfterApproval = await request(other, '/ris/my-returns', 'POST', { risId: approvedRecord.risId, itemId: approvedRecord.itemId, quantity: 1 });
  assert.equal(returnAfterApproval.status, 201);
  assert.equal(returnAfterApproval.body.data.status, 'PENDING');
  const receivedByAdmin = (await request(admin, '/prs')).body.data.find(record => record._id === returnAfterApproval.body.data._id);
  assert.ok(receivedByAdmin);
  assert.equal(receivedByAdmin.returnedBy.name, 'user2 Test');
  assert.equal((await request(user, '/ris/my-items')).body.data.some(row => row.risNumber === 'ADMIN-RECORDED'), false);
  assert.equal((await request(admin, '/ris', 'POST', { ...adminPayload, risNumber: 'UNLINKED', requestedBy: { name: 'Unknown Account' } })).status, 400);
});
