import ValidatedForm from '../components/ValidatedForm';
import { useCallback, useEffect, useState } from 'react';
import axios from 'axios';
import toast from 'react-hot-toast';
import { History, Plus, Search } from 'lucide-react';

const categories = ['IT Equipment', 'Office Equipment', 'Furniture and Fixtures', 'Machinery', 'Communication Equipment', 'Other Property'];
const blank = { propertyName: '', description: '', category: categories[0], acquisitionDate: '', acquisitionCost: '', supplier: '', purchaseOrderNumber: '', sourceOfFund: '', location: '', serialNumber: '', quantity: 1, condition: 'Serviceable', specifications: { brand: '', model: '', processor: '', ram: '', storage: '', operatingSystem: '' } };
const statusLabel = (value) => value?.replaceAll('_', ' ');

export default function PropertiesPage() {
  const [properties, setProperties] = useState([]); const [form, setForm] = useState(blank); const [open, setOpen] = useState(false); const [filters, setFilters] = useState({ search: '', category: '', status: '' }); const [active, setActive] = useState(null); const [action, setAction] = useState('Issue'); const [actionForm, setActionForm] = useState({ custodian: '', office: '', condition: '', remarks: '', expectedQuantity: 1, physicalQuantity: 1 });
  const load = useCallback(async () => { const { data } = await axios.get('/properties', { params: filters }); setProperties(data.data || []); }, [filters]);
  useEffect(() => { const timer = setTimeout(load, 150); return () => clearTimeout(timer); }, [load]);
  const field = (title, key, type = 'text', required = true) => <label className="block text-sm font-medium text-slate-700">{title}<input required={required} type={type} value={form[key] ?? ''} onChange={(e) => setForm({ ...form, [key]: e.target.value })} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2" /></label>;
  const register = async (e) => { e.preventDefault(); try { await axios.post('/properties', { ...form, acquisitionCost: Number(form.acquisitionCost || 0), quantity: Number(form.quantity || 1) }); toast.success('Property registered and code generated.'); setForm(blank); setOpen(false); load(); } catch (error) { toast.error(error.response?.data?.message || 'Unable to register property'); } };
  const startAction = (property, nextAction) => { setActive(property); setAction(nextAction); setActionForm({ custodian: nextAction === 'Transfer' ? property.currentCustodian?.name || '' : '', office: nextAction === 'Transfer' ? property.currentCustodian?.office || '' : '', condition: property.condition || '', remarks: '', expectedQuantity: property.quantity, physicalQuantity: property.quantity }); };
  const submitAction = async (e) => { e.preventDefault(); try { await axios.post(`/properties/${active._id}/actions`, { action, ...actionForm }); toast.success('Property accountability history updated.'); setActive(null); load(); } catch (error) { toast.error(error.response?.data?.message || 'Unable to update property'); } };
  return <div className="space-y-6"><div className="flex flex-wrap justify-between gap-4"><div><h1 className="text-3xl font-semibold">Property Register</h1><p className="text-sm text-slate-500">Complete property lifecycle and accountability records.</p></div><button onClick={() => setOpen(!open)} className="inline-flex items-center gap-2 rounded-xl bg-teal-600 px-4 py-2 font-semibold text-white"><Plus size={17}/>Register property</button></div>
    {open && <ValidatedForm onSubmit={register} className="rounded-2xl border bg-white p-6 shadow-sm"><h2 className="text-xl font-semibold">Property registration</h2><p className="mt-1 text-sm text-slate-500">A unique code is generated automatically when saved.</p><div className="mt-4 grid gap-3 md:grid-cols-3">{field('Property name', 'propertyName', 'text', true)}<label className="text-sm font-medium">Category<select value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })} className="mt-1 w-full rounded-xl border px-3 py-2">{categories.map((category) => <option key={category}>{category}</option>)}</select></label>{field('Acquisition date', 'acquisitionDate', 'date')}{field('Acquisition cost', 'acquisitionCost', 'number')}{field('Supplier', 'supplier')}{field('PO number', 'purchaseOrderNumber')}{field('Source of fund', 'sourceOfFund')}{field('Location', 'location')}{field('Serial number (optional)', 'serialNumber', 'text', false)}{field('Quantity', 'quantity', 'number')}<label className="text-sm font-medium md:col-span-3">Description<textarea required value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} className="mt-1 w-full rounded-xl border px-3 py-2" /></label></div><h3 className="mt-5 font-semibold">Asset specification</h3><div className="mt-2 grid gap-3 md:grid-cols-3">{Object.keys(form.specifications).map((key) => <label key={key} className="text-sm font-medium">{key.replace(/([A-Z])/g, ' $1')}<input value={form.specifications[key]} onChange={(e) => setForm({ ...form, specifications: { ...form.specifications, [key]: e.target.value } })} className="mt-1 w-full rounded-xl border px-3 py-2" /></label>)}</div><button className="mt-5 rounded-xl bg-teal-600 px-4 py-2 font-semibold text-white">Save property</button></ValidatedForm>}
    <div className="rounded-2xl border bg-white p-5 shadow-sm"><div className="grid gap-3 md:grid-cols-3"><label className="relative"><Search size={17} className="absolute left-3 top-3 text-slate-400"/><input value={filters.search} onChange={(e) => setFilters({ ...filters, search: e.target.value })} placeholder="Search code, name, serial, custodian" className="w-full rounded-xl border py-2 pl-9 pr-3"/></label><select value={filters.category} onChange={(e) => setFilters({ ...filters, category: e.target.value })} className="rounded-xl border px-3 py-2"><option value="">All categories</option>{categories.map((value) => <option key={value}>{value}</option>)}</select><select value={filters.status} onChange={(e) => setFilters({ ...filters, status: e.target.value })} className="rounded-xl border px-3 py-2"><option value="">All statuses</option>{['AVAILABLE','ISSUED','IN_USE','TRANSFERRED','RETURNED','UNDER_REPAIR','DAMAGED','LOST','FOR_DISPOSAL','DISPOSED'].map((value) => <option key={value}>{value}</option>)}</select></div><div className="mt-5 space-y-3">{properties.map((property) => <div key={property._id} className="rounded-xl border p-4"><div className="flex flex-wrap justify-between gap-4"><div><b>{property.propertyCode} · {property.propertyName}</b><div className="mt-1 text-sm text-slate-500">{property.category} · S/N {property.serialNumber || '—'} · {property.location || 'No location'}</div><div className="mt-2 text-sm">Custodian: <b>{property.currentCustodian?.name || 'Unassigned'}</b></div></div><div className="text-right"><span className="rounded-full bg-teal-50 px-3 py-1 text-xs font-bold text-teal-800">{statusLabel(property.status)}</span><div className="mt-3 flex gap-2"><button onClick={() => startAction(property, property.currentCustodian?.name ? 'Transfer' : 'Issue')} className="rounded-lg bg-slate-900 px-3 py-2 text-xs font-semibold text-white">{property.currentCustodian?.name ? 'Transfer' : 'Issue'}</button><button onClick={() => startAction(property, 'Physical inventory')} className="rounded-lg border px-3 py-2 text-xs font-semibold">Inventory</button><button onClick={() => startAction(property, 'Report damaged')} className="rounded-lg border px-3 py-2 text-xs font-semibold">Status</button></div></div></div><details className="mt-3 text-sm"><summary className="cursor-pointer font-medium text-slate-600"><History size={15} className="mr-1 inline"/>History ({property.events?.length || 0})</summary>{property.events?.slice().reverse().map((entry, index) => <div key={index} className="mt-2 border-l-2 border-teal-100 pl-3"><b>{new Date(entry.date).toLocaleDateString()} — {entry.action}</b> <span className="text-slate-500">· {statusLabel(entry.status)} {entry.custodian ? `· ${entry.custodian}` : ''} {entry.remarks ? `· ${entry.remarks}` : ''}</span></div>)}</details></div>)}{!properties.length && <p className="py-8 text-center text-sm text-slate-500">No properties found.</p>}</div></div>
    {active && <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/40 p-4"><ValidatedForm onSubmit={submitAction} className="w-full max-w-lg rounded-2xl bg-white p-6"><h2 className="text-xl font-semibold">{action}: {active.propertyCode}</h2><p className="text-sm text-slate-500">This is preserved in the property's audit trail.</p><div className="mt-4 grid gap-3 md:grid-cols-2"><label className="text-sm font-medium">Action<select value={action} onChange={(e) => setAction(e.target.value)} className="mt-1 w-full rounded-xl border p-2">{['Issue','Transfer','Return','Physical inventory','Report damaged','Report lost','Mark for disposal','Dispose'].map((value) => <option key={value}>{value}</option>)}</select></label>{['Issue','Transfer'].includes(action) && <><label className="text-sm font-medium">Custodian<input required value={actionForm.custodian} onChange={(e) => setActionForm({ ...actionForm, custodian: e.target.value })} className="mt-1 w-full rounded-xl border p-2"/></label><label className="text-sm font-medium">Office<input value={actionForm.office} onChange={(e) => setActionForm({ ...actionForm, office: e.target.value })} className="mt-1 w-full rounded-xl border p-2"/></label></>}{action === 'Physical inventory' && <><label className="text-sm font-medium">Expected<input type="number" value={actionForm.expectedQuantity} onChange={(e) => setActionForm({ ...actionForm, expectedQuantity: e.target.value })} className="mt-1 w-full rounded-xl border p-2"/></label><label className="text-sm font-medium">Physical count<input type="number" value={actionForm.physicalQuantity} onChange={(e) => setActionForm({ ...actionForm, physicalQuantity: e.target.value })} className="mt-1 w-full rounded-xl border p-2"/></label></>}<label className="text-sm font-medium md:col-span-2">Condition<input value={actionForm.condition} onChange={(e) => setActionForm({ ...actionForm, condition: e.target.value })} className="mt-1 w-full rounded-xl border p-2"/></label><label className="text-sm font-medium md:col-span-2">Remarks<textarea value={actionForm.remarks} onChange={(e) => setActionForm({ ...actionForm, remarks: e.target.value })} className="mt-1 w-full rounded-xl border p-2"/></label></div><div className="mt-5 flex gap-3"><button className="rounded-xl bg-teal-600 px-4 py-2 font-semibold text-white">Save event</button><button type="button" onClick={() => setActive(null)} className="rounded-xl border px-4 py-2">Cancel</button></div></ValidatedForm></div>}
  </div>;
}
